# 项目相关配置
ruoyi:
  # 名称
  name: RuoYi
  # 版本
  version: 3.8.3
  # 版权年份
  copyrightYear: 2022
  # 实例演示开关
  demoEnabled: true
  # 文件路径 示例（ Windows配置D:/ruoyi/uploadPath，Linux配置 /home/ruoyi/uploadPath）
  profile: /
  # 获取ip地址开关
  addressEnabled: false
  # 验证码类型 math 数组计算 char 字符验证
  captchaType: math

# 开发环境配置
server:
#  ssl:
#    key-store: keystore
#    key-store-password: 123456
#    key-store-type: jks
#    key-store-alias: tomcat

  # 服务器的HTTP端口，默认为8081
  port: 8082
  servlet:
    # 应用的访问路径
    context-path: /chat
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100

# 日志配置
logging:
  level:
    com.ruoyi: debug
    org.springframework: warn

# 用户配置
user:
  password:
    # 密码最大错误次数
    maxRetryCount: 5
    # 密码锁定时间（默认30分钟）
    lockTime: 30

# Spring配置
spring:
  main:
    allow-bean-definition-overriding: true
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles:
    active: druid
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size:  10MB
      # 设置总上传的文件大小
      max-request-size:  20MB
      enabled: true
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  # redis 配置
  redis:
    # 地址
    host: 192.168.254.188
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 5
    # 密码
    password: sky2018#
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: $e7d817bcc28e453ea09d98e6c3fc5783
  # 令牌有效期（默认30分钟）
  expireTime: 30

  redisLoginKey: user_login_tokens

  maxtoken: 1

# MyBatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.ruoyi.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql

minio:
  endpoint: http://192.168.254.188:9000
  accessKey: admin
  secretKey: minio***2022#
  bucketName:  web-image


#rocketmq
rocketmq:
  name-server: dev-rmqnamesrv:9876
  producer:
    group: cloud-ruoyi-group #生产者分组名称
    send-message-timeout: 300000 #发送消息超时(毫秒)
    compress-message-body-threshold: 4096 #压缩消息体阈值，即大于4k的消息体将默认压缩。
    max-message-size: 4194304 #允许的最大消息大小（字节）。
    retry-times-when-send-async-failed: 0 #在异步模式下声明发送失败之前内部执行的最大重试次数
    retry-next-server: true #指示是否在内部发送故障时重试另一个nameServer。
    retry-times-when-send-failed: 2 #在同步模式下声明发送失败之前内部执行的最大重试次数。

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true
  # 请求前缀
  pathMapping: /chat-api

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*

#websocket配置
cim:
  app:
    port: 23456
    enable: false
  websocket:
    enable: true
    port: 34567
    path: /
    protocol: json









